// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS-WlTd0LP5xlJakr67cL-VQ4BaSdTt3E',
    appId: '1:889022882849:web:832c12e98bc0df202e2f60',
    messagingSenderId: '889022882849',
    projectId: 'commerce-back',
    authDomain: 'commerce-back.firebaseapp.com',
    storageBucket: 'commerce-back.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQ5XRDIwDY255adonPSJM2TM5OodDiUs',
    appId: '1:889022882849:android:9e79d036e2d34b6f2e2f60',
    messagingSenderId: '889022882849',
    projectId: 'commerce-back',
    storageBucket: 'commerce-back.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyigHXwHOhJ4fHRprMsPIaaiGHiNPavs',
    appId: '1:889022882849:ios:35dc1db2187a452c2e2f60',
    messagingSenderId: '889022882849',
    projectId: 'commerce-back',
    storageBucket: 'commerce-back.appspot.com',
    iosBundleId: 'com.example.commerceMobile',
  );
}
